server:
  port: 8080
#  ai 配置

spring:
  ai:
    dashscope:
      agent:
        app-id: ${DASHSCOPE_APP_ID}
      api-key: ${DASHSCOPE_API_KEY}
      model: qwen-plus
    openai:
      api-key: ${OPENAI_API_KEY}
      model: qwen-plus
      base-url:
      #      temperature: 0.7
      #      max-tokens: 1024
      #      timeout: 60000
      chat:
        options:
          model: qwen-plus  # 指定DeepSeek模型
          temperature: 1.0      # 控制输出随机性
    #      proxy:
    #        host: ${PROXY_HOST}
    #        port: ${PROXY_PORT}
    #        username: ${PROXY_USERNAME}
    mcp:
      client:
        enabled: true
        version: v1
        request-timeout: 30s
        type: SYNC  # or ASYNC for reactive applications
        name: spring-ai-client
        request:
          timeout: 30s
        sse:
          connections:
            server1:
              url: http://localhost:8081
#              sse-endpoint: /mcp/messages # 暂时不能写 否则启动会找寻这个会报错
        toolcallback:
          enabled: true
#      stdio :
#        root-change-notification: false
#        connections:
#          server1:
#            command: /path/to/server
#            args:
#              - --port=8080
#              - --mode=production
#            env:
#              API_KEY: your-api-key
#              DEBUG: "true"

logging:
  level:
    io.modelcontextprotocol: DEBUG
    org.springframework.web: DEBUG