server:
  port: 8082
#  ai 配置

spring:
  ai:
    dashscope:
      agent:
        app-id: ${DASHSCOPE_APP_ID}
      api-key: ${DASHSCOPE_API_KEY}
      model: qwen-plus
      #      temperature: 0.7
      #      max-tokens: 1024
      #      timeout: 60000
      embedding:
        options:
            model: text-embedding-v4
    vector-store:
      type: Memory
      memory:
        options:
          dimension: 1536
          similarity: cosine
      chat:
        options:
          model: qwen-plus  # 指定DeepSeek模型
          temperature: 1.0      # 控制输出随机性
    #      proxy:
    #        host: ${PROXY_HOST}
    #        port: ${PROXY_PORT}
    #        username: ${PROXY_USERNAME}

app:
  temp-dir: ./temp-docs
  vector-store-file: ./vector_store.json
  chunk-size: 1000
  chunk-overlap: 200

logging:
  level:
    io.modelcontextprotocol: INFO
    org.springframework.web: INFO
    org.springframework.ai: DEBUG
    org.springframework.ai.chat: DEBUG
    org.springframework.ai.embedding: DEBUG
    org.springframework.ai.vectorstore: DEBUG
    org.springframework.ai.vectorstore.memory: DEBUG
#    org.springframework.ai.vectorstore.json: DEBUG
#    org.springframework.ai.vectorstore.json.JsonVectorStore: DEBUG
