server:
  port: 8081
spring:
  ai:
    mcp:
      server:
        name: webmvc-mcp-server
        enabled: true
        version: 1.0.0
        type: ASYNC
        instructions: "This server provides weather information tools and resources"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true


logging:
  level:
    io.modelcontextprotocol: INFO
    org.springframework.web: INFO